# Apply to all files without commiting:
#   pre-commit run --all-files
# Update this file:
#   pre-commit autoupdate
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files
    -   id: detect-private-key
    -   id: check-ast
    -   id: debug-statements
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-yaml
    -   id: check-toml
    -   id: trailing-whitespace
    -   id: mixed-line-ending
    -   id: end-of-file-fixer

-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    -   id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    -   id: isort

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args: [--py38-plus]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports, --python-version=3.8, --install-types, --non-interactive]

-   repo: https://github.com/PyCQA/flake8
    rev: '6.0.0'
    hooks:
    -   id: flake8

-   repo: https://github.com/PyCQA/bandit
    rev: '1.7.4'
    hooks:
    -   id: bandit
        exclude: tests/.*$

-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    - id: black
      language_version: python3.8

-   repo: https://github.com/abravalheri/validate-pyproject
    rev: main
    hooks:
      - id: validate-pyproject
